#!/usr/bin/env bash
set -eou pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app_name=$(basename $(dirname $dir))

# live
  #-e db_uri="$(echo $db_uri)" \
# for test
  #-e jdbc_db_uri="$(echo 'postgres://postgres@192.168.99.100:5432/postgres')" \

docker run --rm -it \
  --name="$(echo $app_name)" \
  --network host \
  -e aws_access_key_id="$(cat ~/.aws/credentials | grep -A 2 skilbjo-robot | grep aws_access_key_id | awk '{print $3}')" \
  -e aws_secret_access_key="$(cat ~/.aws/credentials | grep -A 2 skilbjo-robot | grep aws_secret_access_key | awk '{print $3}')" \
  -e env="$(echo 'dev')" \
  -e db_uri="$(echo $db_uri)" \
  -e circleci_api_key="$(echo $circleci_api_key)" \
  -e influxdb_api_key="$(echo $influxdb_api_key)" \
  -e healthchecks_vacuum="$(echo $healthchecks_vacuum)" \
  "$app_name":dev bash
