#!/usr/bin/env bash
set -eou pipefail

_vacuum(){
  table="$1"
  set +u; _full="$2"; set -u

  if [[ -z $_full ]]; then
    psql "$db_uri" \
      -v ON_ERROR_STOP=1 \
      -c "vacuum verbose analyze ${table};"
  else
    psql "$db_uri" \
      -v ON_ERROR_STOP=1 \
      -c "vacuum full ${table};"
  fi
}
