#!/usr/bin/env bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )" && cd "$dir"
src_dir="${dir}/.."
source "${src_dir}/util"
source "${dir}/util"
util_setup "$dir"

task=''

usage(){ echo "Usage: insights: ${0} [--date <date>] [--task <task>]" 1>&2; exit 1; }
while [[ $# -gt 0 ]]; do
  case "$1" in
    -t|--task)  task="$2"; shift ;;
    --backfill) task='backfill' ;;
    --testing)  task='testing' ;;
    *) break ;;
  esac
  shift
done
if [[ -z $task ]]; then usage; fi

insights(){
  local url="https://circleci.com/api/v2/insights/gh/skilbjo/iris/workflows?circle-token=${circleci_api_key}"
  local url="https://circleci.com/api/v2/insights/gh/skilbjo/iris/workflows/build?circle-token=${circleci_api_key}"
  local url="https://circleci.com/api/v2/insights/gh/skilbjo/iris/workflows/build?branch=master&circle-token=${circleci_api_key}"

  curl "$url"
}

influxdb(){ # https://v2.docs.influxdata.com/v2.0/write-data/
  curl \
    --header "Authorization: Token ${influxdb_api_key}" \
    --data-raw 'mem,host=host1 used_percent=23.43234543 1556896326' \
    'https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/write?org=bf6ebe6c84c539b8&bucket=test'
    #--data-raw 'mem,host=host1 used_percent=23.43234543 1556892576842902000' \
    #--data-raw 'cpu,host=host1 usage_user=3.8234,usage_system=4.23874 1556892726597397000' \
    #--data-raw 'mem,host=host1 used_percent=21.83599203 1556892777007291000' \
}

case "$task" in
  insights ) insights ;;

  influx )   influxdb ;;

  testing ) insights
    echo 'Job complete!' && sleep "$(echo "60 * 60 * 24 * 7" | bc)" ;;

  * ) echo 'In dw-etl but got no args.' && exit 1 ;;
esac

